# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a09f26468a9983bdae2b1d97a4d3ec7e93edce76843538c4caa3588a5cf9c650331c0a9e52b19a45148fcc8e0df5f016a080ab67dc648e242c79daf1c3ed7c5

test:
  secret_key_base: b478c6330a7fd531d2f796d5a1d1f86012da721d58f088ff9ac61983b7c130eedb9d2a1e8309c76f2d0591e3256c7d9704914502eb33c474861656b98bc15c76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
